version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: event-seating-db
    environment:
      POSTGRES_DB: event_seating
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: