server:
  port: 8081

spring:
  application:
    name: ms-event-seating
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/event-ticketing
          jwk-set-uri: http://localhost:8080/realms/event-ticketing/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://localhost:5433/event_seating
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # Changed from validate to update temporarily on first run
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true  # Disable validation temporarily on first run
