spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/event_seating
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

aws:
  s3:
    region: us-east-1
    endpoint: http://localhost:4566
    bucket-name: event-seating-uploads
    access-key: test
    secret-key: test
