spring:
  # --- Database Configuration ---
  datasource:
    url: jdbc:postgresql://localhost:5433/event_seating
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # --- Redis Configuration ---
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000

# --- AWS Configuration for Local Development ---
# This single block now configures all AWS clients (S3, Scheduler, etc.)
# to point to your LocalStack container.
aws:
  region: us-east-1
  s3:
    bucket-name: event-seating-uploads
  local:
    endpoint: http://localhost:4566
    access-key: test
    secret-key: test
