server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/api/event-seating}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: ms-event-seating
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080/realms/event-ticketing}
          jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:8080/realms/event-ticketing/protocol/openid-connect/certs}
  servlet:
    multipart:
      enabled: true
      max-file-size: ${MAX_FILE_SIZE:5MB}
      max-request-size: ${MAX_REQUEST_SIZE:15MB}
      file-size-threshold: 2KB
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
  cache:
    redis:
      time-to-live: 3600s
      key-prefix: "event-seating-ms::"

logging:
  level:
    root: INFO
    com.ticketly: DEBUG

# Application specific configurations
app:
  tier:
    limits:
      FREE:
        max-organizations-per-user: 3
        max-seating-layouts-per-org: 5
        max-active-events: 1
        max-sessions-per-event: 5
      PRO:
        max-organizations-per-user: 10
        max-seating-layouts-per-org: 25
        max-active-events: 10
        max-sessions-per-event: 52
      ENTERPRISE:
        max-organizations-per-user: 100
        max-seating-layouts-per-org: 200
        max-active-events: 1000
        max-sessions-per-event: 200

  # General app config
  seating_layout:
    default-page-size: 6
    default-gap: 25
  organization:
    max-logo-size: 1048576 # 1MB

# AWS EventBridge Scheduler configuration
aws:
  scheduler:
    sqs-queue-arn: ${AWS_SQS_QUEUE_ARN:arn:aws:sqs:us-east-1:000000000000:session-on-sale-queue}
    role-arn: ${AWS_SCHEDULER_ROLE_ARN:arn:aws:iam::000000000000:role/EventBridgeSchedulerRole}
    group-name: ${AWS_SCHEDULER_GROUP_NAME:event-ticketing-schedules}
